#!/usr/bin/env bash
SCRIPT_NAME="logger"

OPT_LD_LIBRARY="logger.so"
OPT_LOG_OUTPUT=""
CMD_ARGV=""

print_usage() {
    echo "usage: ./logger [-o file] [-p sopath] [--] cmd [cmd args ...]"
    echo "    -p: set the path to logger.so, default = ./logger.so"
    echo "    -o: print output to file, print to \"stderr\" if no file specified"
    echo "    --: separate the arguments for logger and for the command"
}

main() {
    args_parsing "$@"

    if [ -n "$OPT_LOG_OUTPUT" ]; then
        LD_PRELOAD="$OPT_LD_LIBRARY" LOGGER_FILE="$OPT_LOG_OUTPUT" "$CMD_ARGV"
    else
        LD_PRELOAD="$OPT_LD_LIBRARY" "$CMD_ARGV"
    fi
}

## Command line arguments parsing
args_parsing() {
    ARG_OPTS="$(getopt -o "p:o:" -n "$SCRIPT_NAME" -- "$@")"
    local retval=$?
    if [ $retval -ne 0 ]; then
        print_usage >&2
        exit 1
    fi

    eval set -- "$ARG_OPTS"

    while true; do
        case "$1" in
            "-p")
                OPT_LD_LIBRARY="$2"
                shift 2
                ;;
            "-o")
                OPT_LOG_OUTPUT="$2"
                shift 2
                ;;
            "--")
                shift
                break
                ;;
            *)
                eprint "$SCRIPT_NAME: unknown error occurred while parsing arguments."
                exit 1
                ;;
        esac
    done

    if [ $# -lt 1 ]; then
        print_usage >&2
        exit 1
    fi
    CMD_ARGV="$@"
}

main "$@"

